export const seed = function seed(knex) {
  return knex('character').del()
    .then(() => knex('character').insert([
      {
        name: 'Rick Sanchez',
        status: 'Alive',
        species: 'Human',
        gender: 'Male',
        image: 'https://rickandmortyapi.com/api/character/avatar/1.jpeg',
        origin: 'Earth (C-137)',
      },
      {
        name: 'Morty Smith',
        status: 'Alive',
        species: 'Human',
        gender: 'Male',
        image: 'https://rickandmortyapi.com/api/character/avatar/2.jpeg',
        origin: 'unknown',
      },
      {
        name: 'Summer Smith',
        status: 'Alive',
        species: 'Human',
        gender: 'Female',
        image: 'https://rickandmortyapi.com/api/character/avatar/3.jpeg',
        origin: 'Earth (Replacement Dimension)',
      },
      {
        name: 'Beth Smith',
        status: 'Alive',
        species: 'Human',
        gender: 'Female',
        image: 'https://rickandmortyapi.com/api/character/avatar/4.jpeg',
        origin: 'Earth (Replacement Dimension)',
      },
      {
        name: 'Jerry Smith',
        status: 'Alive',
        species: 'Human',
        gender: 'Male',
        image: 'https://rickandmortyapi.com/api/character/avatar/5.jpeg',
        origin: 'Earth (Replacement Dimension)',
      },
      {
        name: 'Abadango Cluster Princess',
        status: 'Alive',
        species: 'Alien',
        gender: 'Female',
        image: 'https://rickandmortyapi.com/api/character/avatar/6.jpeg',
        origin: 'Abadango',
      },
      {
        name: 'Abradolf Lincler',
        status: 'unknown',
        species: 'Human',
        gender: 'Male',
        image: 'https://rickandmortyapi.com/api/character/avatar/7.jpeg',
        origin: 'Earth (Replacement Dimension)',
      },
      {
        name: 'Adjudicator Rick',
        status: 'Dead',
        species: 'Human',
        gender: 'Male',
        image: 'https://rickandmortyapi.com/api/character/avatar/8.jpeg',
        origin: 'unknown',
      },
      {
        name: 'Agency Director',
        status: 'Dead',
        species: 'Human',
        gender: 'Male',
        image: 'https://rickandmortyapi.com/api/character/avatar/9.jpeg',
        origin: 'Earth (Replacement Dimension)',
      },
      {
        name: 'Alan Rails',
        status: 'Dead',
        species: 'Human',
        gender: 'Male',
        image: 'https://rickandmortyapi.com/api/character/avatar/10.jpeg',
        origin: 'unknown',
      },
      {
        name: 'Albert Einstein',
        status: 'Dead',
        species: 'Human',
        gender: 'Male',
        image: 'https://rickandmortyapi.com/api/character/avatar/11.jpeg',
        origin: 'Earth (C-137)',
      },
      {
        name: 'Alexander',
        status: 'Dead',
        species: 'Human',
        gender: 'Male',
        image: 'https://rickandmortyapi.com/api/character/avatar/12.jpeg',
        origin: 'Earth (C-137)',
      },
      {
        name: 'Alien Googah',
        status: 'unknown',
        species: 'Alien',
        gender: 'unknown',
        image: 'https://rickandmortyapi.com/api/character/avatar/13.jpeg',
        origin: 'unknown',
      },
      {
        name: 'Alien Morty',
        status: 'unknown',
        species: 'Alien',
        gender: 'Male',
        image: 'https://rickandmortyapi.com/api/character/avatar/14.jpeg',
        origin: 'unknown',
      },
      {
        name: 'Alien Rick',
        status: 'unknown',
        species: 'Alien',
        gender: 'Male',
        image: 'https://rickandmortyapi.com/api/character/avatar/15.jpeg',
        origin: 'unknown',
      },
      {
        name: 'Amish Cyborg',
        status: 'Dead',
        species: 'Alien',
        gender: 'Male',
        image: 'https://rickandmortyapi.com/api/character/avatar/16.jpeg',
        origin: 'unknown',
      },
      {
        name: 'Annie',
        status: 'Alive',
        species: 'Human',
        gender: 'Female',
        image: 'https://rickandmortyapi.com/api/character/avatar/17.jpeg',
        origin: 'Earth (C-137)',
      },
      {
        name: 'Antenna Morty',
        status: 'Alive',
        species: 'Human',
        gender: 'Male',
        image: 'https://rickandmortyapi.com/api/character/avatar/18.jpeg',
        origin: 'unknown',
      },
      {
        name: 'Antenna Rick',
        status: 'unknown',
        species: 'Human',
        gender: 'Male',
        image: 'https://rickandmortyapi.com/api/character/avatar/19.jpeg',
        origin: 'unknown',
      },
      {
        name: 'Ants in my Eyes Johnson',
        status: 'unknown',
        species: 'Human',
        gender: 'Male',
        image: 'https://rickandmortyapi.com/api/character/avatar/20.jpeg',
        origin: 'unknown',
      },
    ]));
};
